### ISSUE TITLE
migrate ws to 2.x

### ISSUE THREAD

**Issue by mkozjak** [qaap/rpc-websockets#5]
Currently the test 1 from server spec fails with:
```
(node:34693) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not running
    1) should return a new instance


  1 failing

  1) Server should return a new instance:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:43010
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)```

**Comment by mkozjak** [comment]
...or switch to uWebSockets #8.
